"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Copy, ShieldOff, UserCheck } from "lucide-react";
import { useState } from "react";
import { EmptyState, PageHeading, SearchSelect, StatusBadge, SurfaceDialog, Tabs } from "@/components/ui/workspace";
import { Disclosure, LoadingSkeleton, MetricStrip, SearchField } from "@/components/ui/insight";
import { AuditItem, PermissionMatrix } from "./identity-components";
import { AppShell } from "@/components/app-shell";
import { adminApi as api } from "./admin-api";

const memberStates: Record<string, string> = { active: "正常", pending_approval: "待审批", pending_email: "待验证邮箱", disabled: "已禁用", password_reset_required: "待重置密码" };

export default function AdminPage() {
  const queryClient = useQueryClient(); const [tab, setTab] = useState("users"); const [notice, setNotice] = useState("");
  const [search, setSearch] = useState(""); const [memberStatus, setMemberStatus] = useState("");
  const users = useQuery({ queryKey: ["admin-users"], queryFn: api.users });
  const roles = useQuery({ queryKey: ["admin-roles"], queryFn: api.roles });
  const permissions = useQuery({ queryKey: ["admin-permissions"], queryFn: api.permissions });
  const audit = useQuery({ queryKey: ["admin-audit"], queryFn: api.audit, enabled: tab === "audit" });
  const action = useMutation({ mutationFn: ({ path, method, body }: { path: string; method: string; body?: unknown }) => api.mutate(path, method, body), onSuccess: async () => { setNotice("变更已保存并写入审计日志。"); await Promise.all([queryClient.invalidateQueries({ queryKey: ["admin-users"] }), queryClient.invalidateQueries({ queryKey: ["admin-roles"] }), queryClient.invalidateQueries({ queryKey: ["admin-audit"] })]); }, onError: (error) => setNotice(error.message) });
  async function createRole(form: FormData) { const selected = permissions.data?.filter((permission) => form.get(permission.code) === "on").map((permission) => permission.code) ?? []; action.mutate({ path: "/roles", method: "POST", body: { code: form.get("code"), name: form.get("name"), description: form.get("description"), permission_codes: selected } }); }
  const visibleUsers = users.data?.filter((user) => (tab !== "requests" || user.status === "pending_approval") && (!memberStatus || user.status === memberStatus) && `${user.email} ${user.display_name ?? ""}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())) ?? [];
  return <AppShell><div className="page admin-page"><PageHeading title="成员与权限" description="管理成员、注册申请和角色权限。管理权限不包含读取其他用户的研究内容。" /><MetricStrip label="成员概况" items={[{ label: "成员", value: users.data?.length }, { label: "待审批", value: users.data?.filter((user) => user.status === "pending_approval").length }, { label: "角色", value: roles.data?.length }]} /><Tabs label="管理模块" value={tab} onChange={setTab} items={[{ value: "users", label: "成员" }, { value: "requests", label: "注册审批" }, { value: "roles", label: "角色与权限" }, { value: "audit", label: "审计记录" }]}>{(users.error || roles.error || permissions.error || audit.error) && <p role="alert" className="form-alert error">无法读取管理信息，请检查访问权限或稍后重试。</p>}{(users.isPending || roles.isPending) && <LoadingSkeleton label="正在读取成员与权限…" />}{notice && <p role="status" className="form-alert admin-notice">{notice}</p>}
    {(tab === "users" || tab === "requests") && <section className="admin-user-list"><div className="identity-filters"><SearchField label="搜索成员" value={search} onChange={setSearch} placeholder="姓名或邮箱…" /><select aria-label="成员状态" value={memberStatus} onChange={(event) => setMemberStatus(event.target.value)}><option value="">全部状态</option>{Object.entries(memberStates).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{users.isSuccess && !visibleUsers.length && <EmptyState title={tab === "requests" ? "没有待处理的注册申请" : "没有匹配的成员"} />}{visibleUsers.map((user) => <article className="panel admin-user" key={user.id}><div className="admin-user-main"><StatusBadge status={user.status} label={memberStates[user.status] ?? user.status} /><h2>{user.display_name || user.email}</h2><p>{user.email}</p><div className="role-chips">{user.role_codes.map((role) => <i key={role}>{roles.data?.find((item) => item.code === role)?.name ?? role}</i>)}</div></div><div className="admin-user-meta"><small>创建于 {new Date(user.created_at).toLocaleDateString()}</small></div><div className="admin-user-actions"><SurfaceDialog title="成员信息" trigger={<button type="button" className="secondary">详情</button>}><dl className="document-metadata"><dt>姓名</dt><dd>{user.display_name || "未设置"}</dd><dt>邮箱</dt><dd>{user.email}</dd><dt>成员编号</dt><dd>{user.id}</dd><dt>创建时间</dt><dd>{new Date(user.created_at).toLocaleString("zh-CN")}</dd></dl></SurfaceDialog>{user.status === "pending_approval" && <button className="primary" onClick={() => action.mutate({ path: `/users/${user.id}/approve`, method: "POST", body: { role_codes: ["researcher"] } })}><UserCheck size={14} /> 批准为研究员</button>}{user.status === "disabled" ? <button className="secondary" onClick={() => action.mutate({ path: `/users/${user.id}/enable`, method: "POST" })}><CheckCircle2 size={14} /> 启用</button> : <button className="danger" onClick={() => action.mutate({ path: `/users/${user.id}/disable`, method: "POST" })}><ShieldOff size={14} /> 禁用</button>}<SearchSelect label="角色" value={user.role_codes[0] ?? ""} disabled={action.isPending} onChange={(value) => action.mutate({ path: `/users/${user.id}/roles`, method: "PUT", body: { role_codes: [value] } })} options={[{ value: "", label: "无角色" }, ...(roles.data ?? []).map(role => ({ value: role.code, label: role.name }))]} /></div></article>)}</section>}
    {tab === "roles" && <div className="admin-role-grid"><PermissionMatrix roles={roles.data ?? []} permissions={permissions.data ?? []} /><section className="panel"><div className="panel-header"><h2>角色目录</h2></div><div className="role-list">{roles.data?.map((role) => <article key={role.id}><div><b>{role.name}</b><span className="mono">{role.code} · {role.is_system ? "SYSTEM" : "CUSTOM"}</span></div><p>{role.description}</p><Disclosure title="角色权限" meta={`${role.permission_codes.length} 项`}><div className="permission-mini">{role.permission_codes.map((code) => <i key={code}>{permissions.data?.find((permission) => permission.code === code)?.name ?? code}</i>)}</div></Disclosure>{!role.is_system && <button className="danger" onClick={() => action.mutate({ path: `/roles/${role.id}`, method: "DELETE" })}>删除</button>}{role.is_system && <button className="secondary" onClick={() => action.mutate({ path: `/roles/${role.id}/copy`, method: "POST", body: { new_code: `${role.code}_copy_${Date.now().toString().slice(-4)}`, new_name: `${role.name} Copy` } })}><Copy size={13} /> 复制</button>}</article>)}</div></section><section className="panel"><div className="panel-header"><h2>组合自定义角色</h2></div><form action={createRole} className="panel-body auth-form"><div className="field"><label htmlFor="role-code">稳定代码</label><input id="role-code" name="code" required pattern="[a-z0-9_.-]+" /></div><div className="field"><label htmlFor="role-name">显示名称</label><input id="role-name" name="name" required /></div><div className="field"><label htmlFor="role-description">说明</label><textarea id="role-description" name="description" /></div><div className="permission-catalog">{Object.entries(Object.groupBy(permissions.data ?? [], (permission) => permission.domain)).map(([domain, items]) => <fieldset key={domain}><legend>{domain}</legend>{items?.map((permission) => <label key={permission.code}><input type="checkbox" name={permission.code} /><span><b>{permission.name}</b><small>{permission.code}</small></span></label>)}</fieldset>)}</div><button className="primary">创建角色</button></form></section></div>}
    {tab === "audit" && <section className="panel"><div className="panel-header"><h2>最近 100 条 IAM 审计事件</h2></div><div>{audit.isPending && <LoadingSkeleton label="正在读取审计记录…" />}{audit.data?.map((event) => <AuditItem key={event.id} event={event} />)}{audit.isSuccess && !audit.data.length && <EmptyState title="暂无审计记录" />}</div></section>}
  </Tabs></div></AppShell>;
}
