"""Generate browser HTTP samples from native SQL snapshots and document DTOs."""

import asyncio
import json
from pathlib import Path

import httpx
from fastapi import FastAPI

from open_deep_research.agentscope_runtime.recovery_store import RecoveryStore
from open_deep_research.agentscope_runtime.research_pipeline import ResearchSnapshot
from open_deep_research.api.native_runs import NativeRuns
from open_deep_research.api.research_router import build_research_router
from open_deep_research.documents.contracts import DocumentChunkView, DocumentSummary
from security.rbac.dependencies import get_current_principal
from tests.auth_helpers import research_principal

TARGET = Path(__file__).resolve().parents[2] / "frontend/src/test/http-contract-samples.ts"


async def sample_source():
    """Capture the actual FastAPI response without coercing away null fields."""
    store = RecoveryStore("sqlite+aiosqlite:///:memory:")
    await store.create_tables()
    service = NativeRuns(store, None, None)
    app = FastAPI()
    app.include_router(build_research_router(service))
    app.dependency_overrides[get_current_principal] = lambda: research_principal("alice")
    try:
        snapshots = []
        async with httpx.AsyncClient(transport=httpx.ASGITransport(app), base_url="http://test") as client:
            for status in ["ready", "completed"]:
                state = ResearchSnapshot(
                    run_id=f"sample-{status}", config_fingerprint="fixture", status=status,
                    final_report="# Sample report" if status == "completed" else "",
                    application={"title": "Sample", "created_at": 1789776000.0},
                )
                await store.create_run("alice", state)
                response = await client.get(f"/runs/{state.run_id}")
                assert response.status_code == 200
                snapshots.append(response.json())
        document = DocumentSummary(
            id="doc-1", filename="sample.txt", media_type="text/plain", size_bytes=6,
            sha256="a" * 64, status="ready", created_at="2026-09-19T00:00:00Z",
            updated_at="2026-09-19T00:00:00Z",
        )
        chunk = DocumentChunkView(id="chunk-1", document_id="doc-1", ordinal=0,
                                  locator="line:1", text="sample")
        samples = {"snapshots": snapshots, "document": document.model_dump(mode="json"),
                   "chunk": chunk.model_dump(mode="json")}
        return (
            "// Generated by tests/as_runtime/frontend_http_samples.py; do not hand-edit.\n"
            'import type { RunSnapshot } from "../lib/contracts/research";\n'
            'import type { ResearchDocument, DocumentChunk } from "../lib/contracts/documents";\n\n'
            "export const httpContractSamples = " + json.dumps(samples, indent=2, ensure_ascii=False)
            + " satisfies { snapshots: RunSnapshot[]; document: ResearchDocument; chunk: DocumentChunk };\n"
        )
    finally:
        await service.aclose()
        await store.aclose()


if __name__ == "__main__":
    TARGET.write_text(asyncio.run(sample_source()), encoding="utf-8")
