"""Generate browser samples through the actual three SSE wire serializers."""

import json
from pathlib import Path

from open_deep_research.agentscope_runtime.recovery_events import public_events

from open_deep_research.api.streams import (
    _publication_sse,
    _sse,
    _task_activity_sse,
)
from open_deep_research.events.public import PublicEvent
from open_deep_research.events.publications import PublicationEvent
from open_deep_research.events.task_activity import PublicTaskActivityEvent

TARGET = Path(__file__).resolve().parents[2] / "frontend/src/test/event-contract-samples.ts"


def sample_source() -> str:
    """Keep nulls and independent cursor domains exactly as served over HTTP."""
    common = {"run_id": "run-1", "dedupe_key": "internal-only"}
    timestamp = "2026-09-19T00:00:00Z"
    events = {
        "runEvents": [
            _sse(PublicEvent(**common, event_id=f"run-{i}", sequence=i,
                            timestamp=timestamp, type=kind, payload={"status": status}))
            for i, kind, status in [(1, "run.started", "running"), (2, "run.completed", "completed")]
        ],
        "taskEvents": [
            _task_activity_sse(PublicTaskActivityEvent(
                **common, task_id="task-1", event_id=f"task-{i}", sequence=i,
                timestamp=timestamp, type=kind, kind="lifecycle", phase=phase,
                status=status, title="任务", summary="公开状态",
            ))
            for i, kind, phase, status in [
                (1, "task.started", "initializing", "running"),
                (2, "task.completed", "terminal", "success"),
            ]
        ],
        "publicationEvents": [
            _publication_sse(PublicationEvent(
                **common, publication_id="pub-1", event_id=f"publication-{i}",
                sequence=i, timestamp=1789776000.0, type=kind, payload={"status": status},
            ))
            for i, kind, status in [
                (1, "publication.started", "running"),
                (2, "publication.completed", "completed"),
            ]
        ],
    }
    events["stageEvents"] = []
    for i, stage in enumerate([
        "summarize_messages", "memory_recall", "clarify_with_user", "write_research_brief",
        "plan_approval", "research_supervisor", "outline_approval", "final_report_generation",
        "memory_extract_and_write",
    ], 1):
        mapped = public_events({"sequence": i, "payload": {
            "type": "research.state", "status": "running", "stage": stage, "completed": [],
        }})
        for kind, public_stage, payload in mapped:
            events["stageEvents"].append(_sse(PublicEvent(
                **common, event_id=f"stage-{i}", sequence=i, timestamp=timestamp,
                type=kind, stage=public_stage, payload=payload,
            )))
    samples = {}
    for domain, frames in events.items():
        samples[domain] = []
        for frame in frames:
            lines = dict(line.split(": ", 1) for line in frame.strip().splitlines())
            event = json.loads(lines["data"])
            assert int(lines["id"]) == event["sequence"]
            assert lines["event"] == event["type"]
            assert "dedupe_key" not in event
            samples[domain].append(event)
    return (
        "// Generated by tests/as_runtime/frontend_contract_samples.py; do not hand-edit.\n"
        'import type { PublicEvent, TaskActivityEvent } from "../lib/contracts/research";\n'
        'import type { PublicationEvent } from "../lib/contracts/publications";\n\n'
        "export const eventContractSamples = " + json.dumps(samples, indent=2, ensure_ascii=False)
        + " satisfies { runEvents: PublicEvent[]; taskEvents: TaskActivityEvent[]; publicationEvents: PublicationEvent[]; stageEvents: PublicEvent[] };\n"
    )


if __name__ == "__main__":
    TARGET.write_text(sample_source(), encoding="utf-8")
