// Generated by tests/as_runtime/frontend_contract_samples.py; do not hand-edit.
import type { PublicEvent, TaskActivityEvent } from "../lib/contracts/research";
import type { PublicationEvent } from "../lib/contracts/publications";

export const eventContractSamples = {
  "runEvents": [
    {
      "schema_version": 2,
      "event_id": "run-1",
      "sequence": 1,
      "run_id": "run-1",
      "type": "run.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": null,
      "payload": {
        "status": "running"
      }
    },
    {
      "schema_version": 2,
      "event_id": "run-2",
      "sequence": 2,
      "run_id": "run-1",
      "type": "run.completed",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": null,
      "payload": {
        "status": "completed"
      }
    }
  ],
  "taskEvents": [
    {
      "schema_version": 1,
      "event_id": "task-1",
      "sequence": 1,
      "run_id": "run-1",
      "task_id": "task-1",
      "timestamp": "2026-09-19T00:00:00Z",
      "type": "task.started",
      "kind": "lifecycle",
      "phase": "initializing",
      "status": "running",
      "title": "任务",
      "summary": "公开状态",
      "iteration": null,
      "duration_ms": null,
      "payload": {}
    },
    {
      "schema_version": 1,
      "event_id": "task-2",
      "sequence": 2,
      "run_id": "run-1",
      "task_id": "task-1",
      "timestamp": "2026-09-19T00:00:00Z",
      "type": "task.completed",
      "kind": "lifecycle",
      "phase": "terminal",
      "status": "success",
      "title": "任务",
      "summary": "公开状态",
      "iteration": null,
      "duration_ms": null,
      "payload": {}
    }
  ],
  "publicationEvents": [
    {
      "schema_version": 1,
      "event_id": "publication-1",
      "sequence": 1,
      "run_id": "run-1",
      "publication_id": "pub-1",
      "type": "publication.started",
      "timestamp": 1789776000.0,
      "payload": {
        "status": "running"
      }
    },
    {
      "schema_version": 1,
      "event_id": "publication-2",
      "sequence": 2,
      "run_id": "run-1",
      "publication_id": "pub-1",
      "type": "publication.completed",
      "timestamp": 1789776000.0,
      "payload": {
        "status": "completed"
      }
    }
  ],
  "stageEvents": [
    {
      "schema_version": 2,
      "event_id": "stage-1",
      "sequence": 1,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "preparing",
      "payload": {
        "stage_id": "preparing",
        "stage_index": 0,
        "stage_count": 6
      }
    },
    {
      "schema_version": 2,
      "event_id": "stage-2",
      "sequence": 2,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "preparing",
      "payload": {
        "stage_id": "preparing",
        "stage_index": 0,
        "stage_count": 6
      }
    },
    {
      "schema_version": 2,
      "event_id": "stage-3",
      "sequence": 3,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "planning",
      "payload": {
        "stage_id": "planning",
        "stage_index": 1,
        "stage_count": 6
      }
    },
    {
      "schema_version": 2,
      "event_id": "stage-4",
      "sequence": 4,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "planning",
      "payload": {
        "stage_id": "planning",
        "stage_index": 1,
        "stage_count": 6
      }
    },
    {
      "schema_version": 2,
      "event_id": "stage-5",
      "sequence": 5,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "planning",
      "payload": {
        "stage_id": "planning",
        "stage_index": 1,
        "stage_count": 6
      }
    },
    {
      "schema_version": 2,
      "event_id": "stage-6",
      "sequence": 6,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "researching",
      "payload": {
        "stage_id": "researching",
        "stage_index": 2,
        "stage_count": 6
      }
    },
    {
      "schema_version": 2,
      "event_id": "stage-7",
      "sequence": 7,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "synthesizing",
      "payload": {
        "stage_id": "synthesizing",
        "stage_index": 3,
        "stage_count": 6
      }
    },
    {
      "schema_version": 2,
      "event_id": "stage-8",
      "sequence": 8,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "writing",
      "payload": {
        "stage_id": "writing",
        "stage_index": 4,
        "stage_count": 6
      }
    },
    {
      "schema_version": 2,
      "event_id": "stage-9",
      "sequence": 9,
      "run_id": "run-1",
      "type": "stage.started",
      "timestamp": "2026-09-19T00:00:00Z",
      "stage": "finalizing",
      "payload": {
        "stage_id": "finalizing",
        "stage_index": 5,
        "stage_count": 6
      }
    }
  ]
} satisfies { runEvents: PublicEvent[]; taskEvents: TaskActivityEvent[]; publicationEvents: PublicationEvent[]; stageEvents: PublicEvent[] };
