// Generated by tests/as_runtime/frontend_http_samples.py; do not hand-edit.
import type { RunSnapshot } from "../lib/contracts/research";
import type { ResearchDocument, DocumentChunk } from "../lib/contracts/documents";

export const httpContractSamples = {
  "snapshots": [
    {
      "run_id": "sample-ready",
      "engine": "agentscope",
      "status": "pending",
      "title": "Sample",
      "created_at": 1789776000.0,
      "revision": 0,
      "pending_human_action": null,
      "pending_security_approvals": [],
      "progress": {
        "status": "pending",
        "current_stage": null,
        "stage_index": 0,
        "stage_count": 6,
        "plan": {},
        "tasks": {
          "total": 0,
          "pending": 0,
          "running": 0,
          "completed": 0,
          "failed": 0,
          "cancelled": 0,
          "timed_out": 0
        },
        "waves": {
          "total": 0,
          "completed": 0
        },
        "latest_findings": [],
        "task_items": {},
        "sources": [],
        "pending_human_action": null,
        "pending_security_approvals": [],
        "report_review": {},
        "last_event_id": 0
      },
      "output": {
        "markdown": "",
        "artifacts": [],
        "publications": [],
        "preferred_output_format": null,
        "publication_theme": null,
        "quality_gate": null,
        "report_review": null,
        "termination_reason": null,
        "status": null,
        "usage": {},
        "usage_accounting": null,
        "metrics": {},
        "completion_status": null,
        "stop_reason": null,
        "uncovered_requirements": [],
        "research_gaps": []
      },
      "last_event_id": 0,
      "events_url": "/runs/sample-ready/events"
    },
    {
      "run_id": "sample-completed",
      "engine": "agentscope",
      "status": "completed",
      "title": "Sample",
      "created_at": 1789776000.0,
      "revision": 0,
      "pending_human_action": null,
      "pending_security_approvals": [],
      "progress": {
        "status": "completed",
        "current_stage": null,
        "stage_index": 0,
        "stage_count": 6,
        "plan": {},
        "tasks": {
          "total": 0,
          "pending": 0,
          "running": 0,
          "completed": 0,
          "failed": 0,
          "cancelled": 0,
          "timed_out": 0
        },
        "waves": {
          "total": 0,
          "completed": 0
        },
        "latest_findings": [],
        "task_items": {},
        "sources": [],
        "pending_human_action": null,
        "pending_security_approvals": [],
        "report_review": {},
        "last_event_id": 0
      },
      "output": {
        "markdown": "# Sample report",
        "artifacts": [],
        "publications": [],
        "preferred_output_format": null,
        "publication_theme": null,
        "quality_gate": null,
        "report_review": null,
        "termination_reason": null,
        "status": null,
        "usage": {},
        "usage_accounting": null,
        "metrics": {},
        "completion_status": null,
        "stop_reason": null,
        "uncovered_requirements": [],
        "research_gaps": []
      },
      "last_event_id": 0,
      "events_url": "/runs/sample-completed/events"
    }
  ],
  "document": {
    "id": "doc-1",
    "filename": "sample.txt",
    "media_type": "text/plain",
    "size_bytes": 6,
    "sha256": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "status": "ready",
    "failure_code": null,
    "page_count": null,
    "chunk_count": 0,
    "ocr_pages": 0,
    "created_at": "2026-09-19T00:00:00Z",
    "updated_at": "2026-09-19T00:00:00Z",
    "deleted_at": null,
    "current_generation_id": null
  },
  "chunk": {
    "id": "chunk-1",
    "document_id": "doc-1",
    "generation_id": null,
    "version_no": null,
    "generation_status": null,
    "location": {},
    "ordinal": 0,
    "locator": "line:1",
    "heading": null,
    "text": "sample"
  }
} satisfies { snapshots: RunSnapshot[]; document: ResearchDocument; chunk: DocumentChunk };
